apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-demo
  generation: 1
  name: nginx-demo
spec:
  rules:
  - host: qdemo.chinawayltd.com
    http:
      paths:
        - backend:
            serviceName: alpine-nginx-02
            servicePort: 80
          path: "/"
