apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-01
spec:
  selector:
    matchLabels:
      app: ingress-nginx-01
  template:
    metadata:
      labels:
        app: ingress-nginx-01
    spec:
      containers:
        - name: ingress-nginx-01
          image: uyinn28/alpine-tool
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c 
                  - echo ${POD_NAME} > /usr/share/nginx/html/index.html
          # command:
          #   - sh
          #   - -c
          # args:
          #   - "echo ${POD_NAME} > /usr/share/nginx/html/index.html"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
