apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  nodeSelector:
    ns: tangxin-test

  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "tail -f /dev/null"]


### ok
### 
# → kgp
# NAME                                 READY     STATUS             RESTARTS   AGE
# two-containers                       2/2       Running            0          7m