apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: alicloud/hangzhou-nas-ssd
            - name: NFS_SERVER
              value: 0000000000-00000.cn-hangzhou.nas.aliyuncs.com
            - name: NFS_PATH
              value: /kubernetes
      volumes:
        - name: nfs-client-root
          nfs:
            server: 0000000000-00000.cn-hangzhou.nas.aliyuncs.com
            path: /kubernetes