apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster1
 annotations:
   volume.beta.kubernetes.io/storage-class: aliyun-gluster-slow
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
