apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    name: nginx-pod1
spec:
  containers:
    - name: nginx-pod1
      image: uyinn28/alpine-tool
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: gluster-vol1
          mountPath: /usr/share/nginx/html
      resources:
        limits:
          cpu: 100
          memory: 100Mi
        requests:
          cpu: 100
          memory: 100Mi
        
  volumes:
    - name: gluster-vol1
      persistentVolumeClaim:
        claimName: gluster1
