# for versions before 1.6.0 use extensions/v1beta1
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-app
  namespace: namespace-assign-to-node
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.15-alpine
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 100Mi